### ISSUE TITLE
Single Collection Issues

### ISSUE THREAD

**Issue by fmorriso** [moseswynn/mongo-jsonschema#1]
Despite what the documentation says, the following does not work as of 2024-06-06:

```
schema = schema_generator.get_schema(
    db='dbname',
    collection='baz',
    sample_percent=.05
)
```

In order to generate the schema for a _**single**_ collection, you must use _**_get_schema**_ with the leading underscore or just use the plural form and pass a single collection name:

```
schema = schema_generator.get_schemas(
    db='dbname',
    collections=['baz'],
    sample_percent=.05
)
```

**Comment by moseswynn** [comment]
@fmorriso The documentation does not say to use `get_schema`.  The `get_schemas` method will handle both a single collection name or a list of collection names. If you are encountering an error, can you please provide the actual error message you are receiving?
